### ISSUE TITLE
Can't load a module from TypeScript using ts-node

### ISSUE THREAD

**Issue by jcubic** [LiosK/UUID.js#13]
got this error:

```
/home/kuba/projects/jcubic/koduj/akademia/quiz/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/kuba/projects/jcubic/koduj/akademia/quiz/node_modules/uuidjs/dist/uuid.js from /home/kuba/projects/jcubic/koduj/akademia/quiz/utils.ts not supported.
Instead change the require of uuid.js in /home/kuba/projects/jcubic/koduj/akademia/quiz/utils.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/home/kuba/projects/jcubic/koduj/akademia/quiz/node_modules/ts-node/dist/index.js:851:20)                                                           
    at Object.<anonymous> (/home/kuba/projects/jcubic/koduj/akademia/quiz/utils.ts:4:18)
    at m._compile (/home/kuba/projects/jcubic/koduj/akademia/quiz/node_modules/ts-node/dist/index.js:857:29)                                                                               
    at require.extensions.<computed> [as .ts] (/home/kuba/projects/jcubic/koduj/akademia/quiz/node_modules/ts-node/dist/index.js:859:16)                                                           
    at Object.<anonymous> (/home/kuba/projects/jcubic/koduj/akademia/quiz/app.ts:21:17)
    at m._compile (/home/kuba/projects/jcubic/koduj/akademia/quiz/node_modules/ts-node/dist/index.js:857:29)                                                                               
    at require.extensions.<computed> [as .ts] (/home/kuba/projects/jcubic/koduj/akademia/quiz/node_modules/ts-node/dist/index.js:859:16)                                                           
    at phase4 (/home/kuba/projects/jcubic/koduj/akademia/quiz/node_modules/ts-node/dist/bin.js:466:20
)                                                                                                   
    at bootstrap (/home/kuba/projects/jcubic/koduj/akademia/quiz/node_modules/ts-node/dist/bin.js:54:12)                                                                                  
    at main (/home/kuba/projects/jcubic/koduj/akademia/quiz/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/home/kuba/projects/jcubic/koduj/akademia/quiz/node_modules/ts-node/dist/bin.js:579:5) {                                                                                
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by LiosK** [comment]
Common JS entry point is not provided. You have to configure your ts-node to use ES Modules.

**Comment by gregkonush** [comment]
What’s the workaround for this for tsnode users?
